NAME	 	= "Special Power Cheat"
VERSION		= "1.0"
TYPE		= "DISABLED"
GAME		= "CNC3TW,CNC3KW"
DESCRIPTION = "Makes some special power available from start"
AUTHOR 		= "Mjstral"
PASTEBIN	= ""

------------------------------------------------------------------
----------------------SCRIPT SECTION------------------------------
------------------------------------------------------------------

SpecialPowerNameTable={
	"ALIENTurretBeamSpecialPower","EMPBlast","EMPBlastGetInRange","EmpBurst","EMPGrenadesGetInRange","GDIPredatorRailSpecialPower","ImprovedEMPBlastGetInRange","MetaGameOp_AlienPhaseField","MetaGameOp_AlienPlague","MetaGameOp_AlienPowerPlanetaryBombardment","MetaGameOp_AlienPowerPlanetaryBombardmentWarhead","MetaGameOp_Base_OBTMTA","MetaGameOp_BuildStrikeForce","MetaGameOp_CancelPendingOperation","MetaGameOp_CONSTRUCT_STRATEGIC_BUILDING",
	"MetaGameOp_CONSTRUCT_STRIKE_FORCE_H","MetaGameOp_CONSTRUCT_STRIKE_FORCE_L","MetaGameOp_CONSTRUCT_STRIKE_FORCE_M","MetaGameOp_CONSTRUCT_STRIKE_FORCE_UH","MetaGameOp_CONSTRUCT_STRIKE_FORCE_UL","MetaGameOp_DecommissionBase","MetaGameOp_DecommissionStrikeForce","MetaGameOp_DetailsBase","MetaGameOp_DetailsStrikeForce","MetaGameOp_GDI_FireHawk_Raid","MetaGameOp_GDI_Power_SpecialForces","MetaGameOp_GDI_Refugee_Aid","MetaGameOp_GDICommandoStrike",
	"MetaGameOp_GDIMediaBlitz","MetaGameOp_GDIPowerIonBlast","MetaGameOp_GDIPowerIonBlastWarhead","MetaGameOp_GDIPowerStateOfEmergency","MetaGameOp_GDISkySentry","MetaGameOp_GDISonicAgitation","MetaGameOp_GDIZocomInfiltration","MetaGameOp_InterceptStrikeForce","MetaGameOp_MoveStrikeForce","MetaGameOp_NOD_Fury_Of_Nod","MetaGameOp_Nod_Power_Black_Hand","MetaGameOp_Nod_Power_Friends_Of_Nod","MetaGameOp_Nod_Power_Kane_Lives","MetaGameOp_Nod_Power_Marked_Of_Kane",
	"MetaGameOp_Nod_Power_Stealth_Field","MetaGameOp_NOD_Rise_Insurection","MetaGameOp_NOD_Sabotage","MetaGameOp_NOD_Vertigo_Strike","MetaGameOp_NodPowerNuclearMissile","MetaGameOp_NodPowerNuclearMissileWarhead","MetaGameOp_NodPowerTiberiumProductionSurge","MetaGameOp_NODPowerTraitor","MetaGameOp_RepairBase","MetaGameOp_ResupplyStrikeForce","MetaGameOp_SCRIN_Alien_Dropship","MetaGameOp_SCRIN_BuildTower","MetaGameOp_SCRIN_Eradicate","MetaGameOp_SCRIN_Ichor_Injection",
	"MetaGameOp_SCRIN_Ion_Superstorm","MetaGameOp_SCRIN_Wormhole","MetaGameOp_SCRINPowerRiftGenerator","MetaGameOp_SCRINPowerRiftGeneratorWarhead","MetaGameOp_StrikeForceBuildBase","MetaGameOp_StrikeForcePatrol","MetaGameOp_StrikeForceUpgrade","MetaGameOp_UpgradeBaseDefense","MetaGameOp_UpgradeBasePower","MetaGameOp_UpgradeBaseTier1","MetaGameOp_UpgradeBaseTier2","MetaGameOp_UpgradeBaseTierDone","NODBeamCannonLaserSpecialPower","NodRageGenerator","NODSignatureGenerator",
	"Notify_Base_Airlift","Notify_Base_OBTMTA","Notify_BuildStrikeForce","Notify_CONSTRUCT_STRATEGIC_BUILDING","Notify_CONSTRUCT_STRIKE_FORCE_H","Notify_CONSTRUCT_STRIKE_FORCE_L","Notify_CONSTRUCT_STRIKE_FORCE_M","Notify_CONSTRUCT_STRIKE_FORCE_UH","Notify_CONSTRUCT_STRIKE_FORCE_UL","Notify_FireHawkRaid","Notify_GDIPowerIonBlast","Notify_ICMUMO_Tier1","Notify_MoveStrikeForce","Notify_NukeStrike","Notify_RepairBase","Notify_ResupplyStrikeForce","Notify_StrikeForceBuildBase",
	"Notify_StrikeForceUpgrade","Notify_UpgradeBaseDefense","Notify_UpgradeBaseTier1","Notify_UpgradeBaseTier2","ShadowSquadBeaconGetInRange","SpecialAbilityHarvest","SpecialAbilityStratoFighter","SpecialPower_AlienSeedTiberium","SpecialPower_AlienShockPods","SpecialPower_AOEMindControl","SpecialPower_AvatarBeamCannon","SpecialPower_AvatarCommandeerDestroyBeamCannon","SpecialPower_AvatarCommandeerDestroyBike","SpecialPower_AvatarCommandeerDestroyFlameTank",
	"SpecialPower_AvatarCommandeerDestroyStealthTank","SpecialPower_AvatarCommandeerDispatch","SpecialPower_AvatarCommandeerGetInRange","SpecialPower_AvatarCommandeerGetInRangeBeam","SpecialPower_AvatarCommandeerGetInRangeBike","SpecialPower_AvatarCommandeerGetInRangeFlame","SpecialPower_AvatarCommandeerGetInRangeStealth","SpecialPower_AvatarCommandeerParalyzeBeamCannon","SpecialPower_AvatarCommandeerParalyzeBike","SpecialPower_AvatarCommandeerParalyzeFlameTank",
	"SpecialPower_AvatarCommandeerParalyzeStealthTank","SpecialPower_AvatarFlamer","SpecialPower_AvatarInvisibility","SpecialPower_AvatarStealthDetect","SpecialPower_BattleshipIntroBombard","SpecialPower_BattleshipSpotTargetBombard","SpecialPower_BlackHandConfessorCabalFireGrenade","SpecialPower_BlackHandConfessorCabalGetToGrenadeRange","SpecialPower_BurrowMines","SpecialPower_ChargeDefensesTrigger","SpecialPower_CloakingField","SpecialPower_ConversionBeam",
	"SpecialPower_ConversionBeamUpgraded","SpecialPower_CrystalShield","SpecialPower_CultistMindControl","SpecialPower_CultistMindControlGetInRange","SpecialPower_DecoyTemple","SpecialPower_DeployBunkerTruck","SpecialPower_DeployIonStorm","SpecialPower_DeployIonStormStart","SpecialPower_FireEMPGrenades","SpecialPower_FireOverloadBeamSelfStunWeapon","SpecialPower_GDIBattleshipRemoveLocomotor","SpecialPower_GDICommandoJumpJet_Dispatch","SpecialPower_GliderLand",
	"SpecialPower_GliderLandDispatch","SpecialPower_GliderLandTrigger","SpecialPower_GliderLiftOff","SpecialPower_GliderLiftOffDispatch","SpecialPower_GliderLiftOffTrigger","SpecialPower_GrantPackUpgrade","SpecialPower_GrantUnpackUpgrade","SpecialPower_ImprovedSonicTankOverloadBeam","SpecialPower_JumpJetPlaceSatchelCharge","SpecialPower_JumpJetPlaceSatchelCharge_NOD","SpecialPower_LaserFencing","SpecialPower_LightningSpike","SpecialPower_MagneticMines",
	"SpecialPower_ManipulateObject","SpecialPower_MarkedOfKaneCloakingField","SpecialPower_MechapedeAddDiskModule","SpecialPower_MechapedeAddRazorModule","SpecialPower_MechapedeAddShardModule","SpecialPower_MechapedeAddTioxinModule","SpecialPower_MjolnirStrike","SpecialPower_OverlordsWrath","SpecialPower_PhaseField","SpecialPower_PlaceBoobyTrapAtBridge","SpecialPower_PlaceBoobyTrapAtBuilding","SpecialPower_PlaceBoobyTrapAtHusk","SpecialPower_PlaceBoobyTrapAtTechBuilding",
	"SpecialPower_PlaceBoobyTrapDispatch","SpecialPower_PlaceSatchelCharge","SpecialPower_PlaceSatchelCharge_NOD","SpecialPower_PlaceSatchelChargeSticky_NOD","SpecialPower_PowerSignatureScan","SpecialPower_RailgunAccelerator","SpecialPower_Reaper17TiberiumVibrationScan","SpecialPower_RecallAllAircraft","SpecialPower_Redemption","SpecialPower_ReflectorAttack","SpecialPower_ReturnToDock","SpecialPower_RiftGeneratorWeapon","SpecialPower_SatchelCharge_Dispatch",
	"SpecialPower_SonicRepulsionField","SpecialPower_SpotBeaconBombard","SpecialPower_SpotTargetBombard","SpecialPower_SummonMothership","SpecialPower_SummonTibHive","SpecialPower_SupersonicAirAttack","SpecialPower_Swarm","SpecialPower_TargetedRepairVehicle","SpecialPower_TeleportEradicator","SpecialPower_TemporalWormhole","SpecialPower_TiberiumVibrationScan","SpecialPower_Traveler59WormHole","SpecialPower_UseBlinkPack","SpecialPower_UseTiberiumAgitation",
	"SpecialPower_UseTraveler59BlinkPack","SpecialPower_WormHole","SpecialPowerAirDispersion","SpecialPowerAlienRepairDrones","SpecialPowerBombingRun","SpecialPowerCallAirstrike","SpecialPowerCallAirstrikeSPWashington","SpecialPowerCallForTransportGDI","SpecialPowerCallForTransportNOD","SpecialPowerCallForTransportSteelTalons","SpecialPowerCallForTransportZOCOM","SpecialPowerCallSupportBloodhound","SpecialPowerCallSupportGDIAirborne","SpecialPowerCallSupportHunterKillerTeam",
	"SpecialPowerCallSupportSTBloodhound","SpecialPowerCallSupportZOCOMAirborne","SpecialPowerCallSupportZOCOMBloodhound","SpecialPowerCallSupportZOCOMHunterKillerTeam","SpecialPowerCaptureControlPoint","SpecialPowerCloneObjectSelect","SpecialPowerCloneObjectSpawn","SpecialPowerCombineWithUnit","SpecialPowerComputerCounterMeasures","SpecialPowerDecoyNuclearMissileTimer","SpecialPowerDeployBeacon","SpecialPowerDisguise","SpecialPowerDispatchRadarJammingMissile",
	"SpecialPowerDisruptionPod_Dispatch","SpecialPowerDisruptionPod_Targeted","SpecialPowerDisruptionPod_UnTargeted","SpecialPowerDummyTriggered1","SpecialPowerDummyTriggered2","SpecialPowerDummyTriggered3","SpecialPowerEMPControlCenter","SpecialPowerGDI_APCMinefield","SpecialPowerGDI_SpaceCommandDropPods","SpecialPowerGDI_SpaceCommandShockwaveArtillery","SpecialPowerGDINuclearMissile","SpecialPowerGetToJumpJetRange","SpecialPowerInfantryDigIn","SpecialPowerInfantryDigInTrigger",
	"SpecialPowerIonCannonControlIonCannon","SpecialPowerIonCannonControlIonCannon_2_1","SpecialPowerJumpJetDispatch","SpecialPowerJumpJetHordeTrigger","SpecialPowerLaunchCatalystMissile","SpecialPowerMastermindTeleportObject","SpecialPowerMastermindTeleportObjectSelect","SpecialPowerMoveToPositionAndEvacuate","SpecialPowerNuclearMissile","SpecialPowerProdigyTeleportObject","SpecialPowerProdigyTeleportObjectSelect","SpecialPowerPulseScan","SpecialPowerRadarJamMissile",
	"SpecialPowerRadarScan","SpecialPowerRedShadowStrikeTeam","SpecialPowerReturnToProducer","SpecialPowerSeedTiberium","SpecialPowerSensorPod_Dispatch","SpecialPowerSensorPod_Targeted","SpecialPowerSensorPod_UnTargeted","SpecialPowerTibVeinDetonation","SpecialPowerTriggerJumpJets","SpecialPowerUncombineWithUnit","SpecialPowerZOCOM_SpaceCommandRaiderPods","SpecialPowerZOCOMBombingRun","SteelTalonsAdaptiveArmor","TiberiumAgitationGetInRange"
}

SpecialPowerSelection = { "SpecialPower_WormHole","EMPBlast","SpecialPower_CrystalShield" }

PLAYER = "<Local Player>"
SPECIAL_POWER_AVAILABILITY 	= { "Available", "Disabled", "ForcedAvailable", "Hidden" }
for i=1,getn(SpecialPowerSelection),1 do
	ExecuteAction("PLAYER_SPECIAL_POWER_AVAILABILITY", PLAYER, SpecialPowerSelection[i], "ForcedAvailable")
	--ExecuteAction("PLAYER_UNIT_TYPE_SPECIAL_POWER_IGNORE_REQUIREMENTS", PLAYER, OBJECT_TYPE, SpecialPowerSelection[i], 0)
	ExecuteAction("PLAYER_SET_SPECIAL_POWER_COUNTDOWN", PLAYER, SpecialPowerSelection[i], 0)
end
